// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	attributes "github.com/zdarovich/promotion-api/internal/repositories/attributes"
)

// IRepository is an autogenerated mock type for the IRepository type
type IRepository struct {
	mock.Mock
}

// DeleteAttributesByCampaignID provides a mock function with given fields: campaignID
func (_m *IRepository) DeleteAttributesByCampaignID(campaignID int) error {
	ret := _m.Called(campaignID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(campaignID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAttribute provides a mock function with given fields: campaignID
func (_m *IRepository) GetAttribute(campaignID int) ([]attributes.Attribute, error) {
	ret := _m.Called(campaignID)

	var r0 []attributes.Attribute
	if rf, ok := ret.Get(0).(func(int) []attributes.Attribute); ok {
		r0 = rf(campaignID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]attributes.Attribute)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(campaignID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAttributes provides a mock function with given fields: campaignIDs
func (_m *IRepository) GetAttributes(campaignIDs []int) (map[int][]*attributes.Attribute, error) {
	ret := _m.Called(campaignIDs)

	var r0 map[int][]*attributes.Attribute
	if rf, ok := ret.Get(0).(func([]int) map[int][]*attributes.Attribute); ok {
		r0 = rf(campaignIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int][]*attributes.Attribute)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]int) error); ok {
		r1 = rf(campaignIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveAttributes provides a mock function with given fields: c
func (_m *IRepository) SaveAttributes(c []*attributes.Attribute) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func([]*attributes.Attribute) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAttribute provides a mock function with given fields: c
func (_m *IRepository) UpdateAttribute(c attributes.Attribute) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(attributes.Attribute) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
