// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	databasediscovery "github.com/zdarovich/promotion-api/internal/service/databasediscovery"
)

// IDatabaseDiscovery is an autogenerated mock type for the IDatabaseDiscovery type
type IDatabaseDiscovery struct {
	mock.Mock
}

// GetDatabase provides a mock function with given fields: clientCode
func (_m *IDatabaseDiscovery) GetDatabase(clientCode string) (databasediscovery.Database, error) {
	ret := _m.Called(clientCode)

	var r0 databasediscovery.Database
	if rf, ok := ret.Get(0).(func(string) databasediscovery.Database); ok {
		r0 = rf(clientCode)
	} else {
		r0 = ret.Get(0).(databasediscovery.Database)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(clientCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
