// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IGinContext is an autogenerated mock type for the IGinContext type
type IGinContext struct {
	mock.Mock
}

// PostForm provides a mock function with given fields: key
func (_m *IGinContext) PostForm(key string) string {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
