// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	root "github.com/zdarovich/promotion-api/internal/api/requests/root"
	response "github.com/zdarovich/promotion-api/internal/api/response"
)

// IRoot is an autogenerated mock type for the IRoot type
type IRoot struct {
	mock.Mock
}

// Handle provides a mock function with given fields: context
func (_m *IRoot) Handle(context root.IGinContext) (*response.Data, error) {
	ret := _m.Called(context)

	var r0 *response.Data
	if rf, ok := ret.Get(0).(func(root.IGinContext) *response.Data); ok {
		r0 = rf(context)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.Data)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(root.IGinContext) error); ok {
		r1 = rf(context)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
