// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	user "github.com/zdarovich/promotion-api/internal/repositories/user"
)

// IRepository is an autogenerated mock type for the IRepository type
type IRepository struct {
	mock.Mock
}

// GetUser provides a mock function with given fields: username
func (_m *IRepository) GetUser(username string) (user.User, error) {
	ret := _m.Called(username)

	var r0 user.User
	if rf, ok := ret.Get(0).(func(string) user.User); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserBySessionKey provides a mock function with given fields: sessionKey
func (_m *IRepository) GetUserBySessionKey(sessionKey string) (user.User, error) {
	ret := _m.Called(sessionKey)

	var r0 user.User
	if rf, ok := ret.Get(0).(func(string) user.User); ok {
		r0 = rf(sessionKey)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sessionKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
