// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	config "github.com/zdarovich/promotion-api/internal/repositories/config"
)

// IRepository is an autogenerated mock type for the IRepository type
type IRepository struct {
	mock.Mock
}

// GetConfigByName provides a mock function with given fields: name
func (_m *IRepository) GetConfigByName(name string) (config.Conf, error) {
	ret := _m.Called(name)

	var r0 config.Conf
	if rf, ok := ret.Get(0).(func(string) config.Conf); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(config.Conf)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
