// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IGinContext is an autogenerated mock type for the IGinContext type
type IGinContext struct {
	mock.Mock
}

// Abort provides a mock function with given fields:
func (_m *IGinContext) Abort() {
	_m.Called()
}

// JSON provides a mock function with given fields: code, obj
func (_m *IGinContext) JSON(code int, obj interface{}) {
	_m.Called(code, obj)
}

// PostForm provides a mock function with given fields: _a0
func (_m *IGinContext) PostForm(_a0 string) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
