// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	response "github.com/zdarovich/promotion-api/internal/api/response"
)

// IResponse is an autogenerated mock type for the IResponse type
type IResponse struct {
	mock.Mock
}

// Error provides a mock function with given fields: context, err
func (_m *IResponse) Error(context response.IGinContext, err error) *response.ErrorResponse {
	ret := _m.Called(context, err)

	var r0 *response.ErrorResponse
	if rf, ok := ret.Get(0).(func(response.IGinContext, error) *response.ErrorResponse); ok {
		r0 = rf(context, err)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ErrorResponse)
		}
	}

	return r0
}

// OK provides a mock function with given fields: context, responseData
func (_m *IResponse) OK(context response.IGinContext, responseData *response.Data) *response.SuccessResponse {
	ret := _m.Called(context, responseData)

	var r0 *response.SuccessResponse
	if rf, ok := ret.Get(0).(func(response.IGinContext, *response.Data) *response.SuccessResponse); ok {
		r0 = rf(context, responseData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.SuccessResponse)
		}
	}

	return r0
}
