// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	session "github.com/zdarovich/promotion-api/internal/repositories/session"
)

// IRepository is an autogenerated mock type for the IRepository type
type IRepository struct {
	mock.Mock
}

// GetSessionByKey provides a mock function with given fields: sessionKey
func (_m *IRepository) GetSessionByKey(sessionKey string) (session.Session, error) {
	ret := _m.Called(sessionKey)

	var r0 session.Session
	if rf, ok := ret.Get(0).(func(string) session.Session); ok {
		r0 = rf(sessionKey)
	} else {
		r0 = ret.Get(0).(session.Session)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sessionKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
