// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	campaign "github.com/zdarovich/promotion-api/internal/repositories/campaign"
)

// IRepository is an autogenerated mock type for the IRepository type
type IRepository struct {
	mock.Mock
}

// DeleteCampaigns provides a mock function with given fields: campaignID
func (_m *IRepository) DeleteCampaigns(campaignID int) error {
	ret := _m.Called(campaignID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(campaignID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCampaigns provides a mock function with given fields: campaignID, campaignType, records, page
func (_m *IRepository) GetCampaigns(campaignID int, campaignType string, records int, page int) ([]campaign.Campaign, error) {
	ret := _m.Called(campaignID, campaignType, records, page)

	var r0 []campaign.Campaign
	if rf, ok := ret.Get(0).(func(int, string, int, int) []campaign.Campaign); ok {
		r0 = rf(campaignID, campaignType, records, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]campaign.Campaign)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string, int, int) error); ok {
		r1 = rf(campaignID, campaignType, records, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCampaignsCount provides a mock function with given fields: campaignID, campaignType
func (_m *IRepository) GetCampaignsCount(campaignID int, campaignType string) (int, error) {
	ret := _m.Called(campaignID, campaignType)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, string) int); ok {
		r0 = rf(campaignID, campaignType)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(campaignID, campaignType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveCampaigns provides a mock function with given fields: c
func (_m *IRepository) SaveCampaigns(c *campaign.Campaign) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*campaign.Campaign) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCampaigns provides a mock function with given fields: c
func (_m *IRepository) UpdateCampaigns(c campaign.Campaign) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(campaign.Campaign) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
