// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-01-20 13:56:25.249173399 +0200 EET m=+1.236505111

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "post": {
                "description": "Save campaign",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "campaign"
                ],
                "summary": "Save campaign",
                "parameters": [
                    {
                        "type": "string",
                        "description": "session key",
                        "name": "sessionKey",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "client code",
                        "name": "clientCode",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "client code",
                        "name": "request",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "campaign IDs - (1,4,7)",
                        "name": "campaignID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "2006-01-02",
                        "name": "startDate",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "2006-01-02",
                        "name": "endDate",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "test",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "1",
                        "name": "warehouseID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "1",
                        "name": "purchasedAmount",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "1",
                        "name": "purchaseTotalValue",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "1",
                        "name": "purchasedProductGroupID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "1",
                        "name": "specialPrice",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "1",
                        "name": "percentageOff",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "1",
                        "name": "sumOff",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "1",
                        "name": "awardedProductGroupID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "1",
                        "name": "percentageOffMatchingItems",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "1",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.ErrorResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "Status"
                }
            }
        }
    },
    "tags": [
        {
            "name": "general"
        },
        {
            "name": "campaign"
        }
    ]
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.3",
	BasePath:    "/api/v1/",
	Schemes:     []string{},
	Title:       "Promotion API",
	Description: "POC of promotion API",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
