// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IIdentity is an autogenerated mock type for the IIdentity type
type IIdentity struct {
	mock.Mock
}

// GenerateNewJWT provides a mock function with given fields: clientCode, sessionKey
func (_m *IIdentity) GenerateNewJWT(clientCode string, sessionKey string) (string, error) {
	ret := _m.Called(clientCode, sessionKey)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(clientCode, sessionKey)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(clientCode, sessionKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
